# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtsR10WyJGJO-QBK6J25zCHLMHid56PI
"""

!pip install gradio

import json
import gradio as gr
import re

def convert_case(key, style):

    if style == "snake_case":
        return re.sub(r'(?<!^)(?=[A-Z])', '_', key).lower()

    if style == "camelCase":
        words = key.split("_")
        return words[0] + ''.join(word.capitalize() for word in words[1:])

    if style == "PascalCase":
        return ''.join(word.capitalize() for word in key.split("_"))

    if style == "kebab-case":
        return key.replace("_", "-")

    return key

def remove_nulls(data):

    if isinstance(data, dict):
        return {k: remove_nulls(v) for k, v in data.items() if v is not None}

    if isinstance(data, list):
        return [remove_nulls(v) for v in data]

    return data

def text_to_json(text):

    data = {}

    lines = text.strip().split("\n")

    for line in lines:

        if ":" not in line:
            continue

        key, value = line.split(":",1)

        key = key.strip()
        value = value.strip()

        try:
            value = json.loads(value)
        except:
            pass

        data[key] = value

    return data

def json_stats(data):

    stats = {}

    stats["Top-level Keys"] = len(data)

    total = 0
    arrays = False
    nested = False

    def scan(obj):
        nonlocal total, arrays, nested

        if isinstance(obj, dict):
            total += len(obj)

            for v in obj.values():
                if isinstance(v, dict):
                    nested = True
                if isinstance(v, list):
                    arrays = True
                scan(v)

        if isinstance(obj, list):
            arrays = True
            for v in obj:
                scan(v)

    scan(data)

    stats["Total Keys"] = total
    stats["Has Arrays"] = arrays
    stats["Has Nested Objects"] = nested

    return stats

def process_json(input_text, case_style, remove_null, pretty):

    try:

        data = text_to_json(input_text)

        if remove_null:
            data = remove_nulls(data)

        new_data = {}

        for k,v in data.items():
            new_data[convert_case(k,case_style)] = v

        data = new_data

        if pretty:
            output = json.dumps(data,indent=4)
        else:
            output = json.dumps(data)

        stats = json_stats(data)

        stats_text = "\n".join([f"{k}: {v}" for k,v in stats.items()])

        return output, "Successfully converted to JSON!", stats_text

    except Exception as e:

        return "", f"Error: {str(e)}", ""

with gr.Blocks(title="JSON Refiner Advanced Edition") as demo:

    gr.Markdown("# JSON Refiner Advanced Edition")
    gr.Markdown("Professional JSON Processing Tool")

    with gr.Row():

        with gr.Column():

            input_text = gr.Textbox(
                label="Key-Value Input",
                lines=12,
                placeholder="name: John Doe\nage: 28\nis_active: true"
            )

            case_style = gr.Radio(
                ["snake_case","camelCase","PascalCase","kebab-case"],
                value="snake_case",
                label="Key Case Style"
            )

            remove_null = gr.Checkbox(label="Remove Nulls")

            pretty = gr.Checkbox(label="Pretty Print", value=True)

            btn = gr.Button("Refine JSON")

        with gr.Column():

            output_json = gr.Code(label="Refined JSON", language="json")

            status = gr.Textbox(label="Status")

            stats = gr.Textbox(label="JSON Statistics")

    btn.click(
        process_json,
        inputs=[input_text,case_style,remove_null,pretty],
        outputs=[output_json,status,stats]
    )

demo.launch()